[workspace]
authors = ["dohan <dyh0514@gmail.com>"]
channels = ["conda-forge", "robostack-humble"]
name = "HRI_Drone_project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "colcon build --packages-select hri_drone_project"
clean = "rm -rf build install log"
test_sensor = { cmd = "ros2 run hri_drone_project Test_Sensor_Node", env = { LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH", AMENT_PREFIX_PATH = "$CONDA_PREFIX:$PWD/install/hri_drone_project" } }
test_processor = { cmd = "ros2 run hri_drone_project Signal_Processor_Test", env = { LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH", AMENT_PREFIX_PATH = "$CONDA_PREFIX:$PWD/install/hri_drone_project" } }

[dependencies]
# 드론 프로젝트의 핵심 로직과 통신만 남긴 Lightweight 구성입니다.
pyserial = ">=3.5,<4"
ros-humble-foxglove-bridge = ">=0.8.5,<0.9"
eigen = ">=3.4.0,<4"
ros-humble-sensor-msgs = ">=4.9.0,<5"
ros-humble-tf2-geometry-msgs = ">=0.25.14,<0.26"
ros-humble-vision-opencv = ">=3.2.1,<4"
jupyter = ">=1.1.1,<2"
